### ISSUE TITLE
Completes with false success when git fetch fails

### ISSUE THREAD

**Issue by jordandrako** [microsoft/beachball#195]
Node version: 10.15.1
Beachball version: 1.14.2

When I run `beachball check|bump|publish`, any command that checks against origin/master from bamboo CI, and it fails to fetch (separate issue with bamboo environment preventing fetch from working), the command completes with a success even though it should either fail or try to publish packages.

Error log:
```
build	06-Nov-2019 18:57:33	
build	06-Nov-2019 18:57:33	> root@0.0.1 checkchange /home/bamboo/bamboo-agent-home/xml-data/build-dir/[REDACTED]
build	06-Nov-2019 18:57:33	> beachball check --changehint "Run 'yarn change' to generate a change file"
build	06-Nov-2019 18:57:33	
build	06-Nov-2019 18:57:33	Defaults to "origin"
build	06-Nov-2019 18:57:33	Target branch is "origin/master"
build	06-Nov-2019 18:57:33	Checking for changes against "origin/master"
build	06-Nov-2019 18:57:33	fetching latest from remotes
error	06-Nov-2019 18:57:33	Cannot fetch remote: origin
error	06-Nov-2019 18:57:33	(node:8896) UnhandledPromiseRejectionWarning: Error: Cannot fetch
error	06-Nov-2019 18:57:33	    at Object.fetchRemote (/home/bamboo/bamboo-agent-home/xml-data/build-dir/[REDACTED]/node_modules/beachball/lib/git.js:81:15)
error	06-Nov-2019 18:57:33	    at Object.getChangedPackages (/home/bamboo/bamboo-agent-home/xml-data/build-dir/[REDACTED]/node_modules/beachball/lib/getChangedPackages.js:49:15)
error	06-Nov-2019 18:57:33	    at Object.isChangeFileNeeded (/home/bamboo/bamboo-agent-home/xml-data/build-dir/[REDACTED]/node_modules/beachball/lib/validation.js:9:50)
error	06-Nov-2019 18:57:33	    at /home/bamboo/bamboo-agent-home/xml-data/build-dir/[REDACTED]/node_modules/beachball/lib/cli.js:70:41
error	06-Nov-2019 18:57:33	    at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/[REDACTED]/node_modules/beachball/lib/cli.js:107:3)
error	06-Nov-2019 18:57:33	    at Module._compile (internal/modules/cjs/loader.js:689:30)
error	06-Nov-2019 18:57:33	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
error	06-Nov-2019 18:57:33	    at Module.load (internal/modules/cjs/loader.js:599:32)
error	06-Nov-2019 18:57:33	    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
error	06-Nov-2019 18:57:33	    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error	06-Nov-2019 18:57:33	(node:8896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
error	06-Nov-2019 18:57:33	(node:8896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
simple	06-Nov-2019 18:57:33	Finished task 'Check for changes' with result: Success
simple	06-Nov-2019 18:57:33	Starting task 'Publish changes' of type 'com.atlassian.bamboo.plugins.bamboo-nodejs-plugin:task.builder.npm'
```

**Comment by kenotron** [comment]
Good catch! Just had another report offline from another person who hit this. This I'll fix right away!

**Comment by kenotron** [comment]
publish seems to be doing good with gitFailFast, I think we should fail fast on all git operations.

**Comment by jordandrako** [comment]
Thanks Ken!
