### ISSUE TITLE
Bumping a Version Group Infinitely Recurses When Only Prerelease Versions Allowed

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/beachball#364]
Steps to repro:

1. Create a version group around prerelease packages
2. Set the version group to only allow prereleases
3. Run `npx beachball bump`

Expected behavior:
Packages are bumped

Actual behavior:
Exception due to infinite recursion:
```
An error has been detected while running beachball!
RangeError: Maximum call stack size exceeded
    at C:\Users\nickg\Desktop\react-native-windows\node_modules\beachball\lib\bump\updateRelatedChangeType.js:21:55
    at Array.forEach (<anonymous>)
    at updateRelatedChangeType (C:\Users\nickg\Desktop\react-native-windows\node_modules\beachball\lib\bump\updateRelatedChangeType.js:21:47)
    at C:\Users\nickg\Desktop\react-native-windows\node_modules\beachball\lib\bump\updateRelatedChangeType.js:29:17
    at Array.forEach (<anonymous>)
    at updateRelatedChangeType (C:\Users\nickg\Desktop\react-native-windows\node_modules\beachball\lib\bump\updateRelatedChangeType.js:27:47)
    at C:\Users\nickg\Desktop\react-native-windows\node_modules\beachball\lib\bump\updateRelatedChangeType.js:29:17
    at Array.forEach (<anonymous>)
    at updateRelatedChangeType (C:\Users\nickg\Desktop\react-native-windows\node_modules\beachball\lib\bump\updateRelatedChangeType.js:27:47)
    at C:\Users\nickg\Desktop\react-native-windows\node_modules\beachball\lib\bump\updateRelatedChangeType.js:29:17
```

The failing code is around here: https://github.com/microsoft/beachball/blob/master/packages/beachball/src/bump/updateRelatedChangeType.ts#L42-L46

Example config:
```json
"beachball": {
    "gitTags": false,
    "groups": [
      {
        "name": "React Native Windows Packages",
        "include": [
          "packages/@react-native-windows/*",
          "vnext"
        ],
        "disallowedChangeTypes": [
          "major",
          "minor",
          "patch"
        ]
      }
    ]
  },
```

**Comment by NickGerleman** [comment]
Adding some logging, `packageChangeTypes[pkgName]` for react-native-windows is initially evaluated to prerelease, but later 
evaluates incorrectly to patch. 

```ts
  // Handle groups
  packageChangeTypes[pkgName] = getMaxChangeType(changeType, packageChangeTypes[pkgName], disallowedChangeTypes);
```

**Comment by prprabhu-ms** [comment]
I can confirm that this behaviour still exists.

As a workaround, I disabled `bumpDeps` in our beachball configuration: https://github.com/Azure/communication-ui-library/pull/773

My guess is that this is caused  by a conflict in how dependent packages and groups work:

* By default, changefiles are created with `"dependentChangeType": "patch"`.
* `patch` type is considered to be higher than `prerelease` (the order is `none, prerelease, patch, ...`)
* When trying to determine the change type for a group where only `prerelease` type is allowed, a dependent package withing the group gets assigned the type `patch` because of `bumpDeps` and some default changefile.
* At that point, the logic for determining the type for group gets stuck because `patch` isn't allowed.

For instance, I could make the infinite recursion go away by replacing  `"dependentChangeType": "patch"` with  `"dependentChangeType": "none"` in all our change files.
