### ISSUE TITLE
Cannot commit changes with `beachball change` command

### ISSUE THREAD

**Issue by abjutus** [microsoft/beachball#949]
## Description

The change file was generated successfully and staged, but it cannot be committed.

## Error Message

```
Error: Cannot commit changes: Cannot commit changes:  error: pathspec '/Users/xxx/play-beachball/change/*.json' did not match any file(s) known to git
    at commit (/Users/xxx/play-beachball/node_modules/.pnpm/workspace-tools@0.36.4/node_modules/workspace-tools/lib/git/gitUtilities.js:200:15)
    at writeChangeFiles (/Users/xxx/play-beachball/node_modules/.pnpm/beachball@2.40.0/node_modules/beachball/lib/changefile/writeChangeFiles.js:44:38)
    at change (/Users/xxx/play-beachball/node_modules/.pnpm/beachball@2.40.0/node_modules/beachball/lib/commands/change.js:40:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/xxx/play-beachball/node_modules/.pnpm/beachball@2.40.0/node_modules/beachball/lib/cli.js:55:13
```

**Comment by ecraig12345** [comment]
Sorry for the slow response. There's not enough info from that log to debug, so if you're still having this issue, please either add more detailed repro steps, or make a repro in a GitHub repo.
