### ISSUE TITLE
Issue with shallow clones in CI

### ISSUE THREAD

**Issue by kwickramasekara** [microsoft/beachball#953]
We just updated Beachball from `2.31.5` to `2.41.0` and noticed that in CI (Azure Devops) its having trouble deepening the commits. 

Output from CI:

```
> beachball check


Validating options and change files...
Checking for changes against "origin/main"
This is a shallow clone. Deepening to check for changes...
Deepening by 100 more commits (attempt 1/3)...
beachball v2.41.0 - the sunniest version bumping tool
An error has been detected while running beachball!
Error: Failed to fetch more history (see above for details)
    at deepenHistory (/home/vsts/work/1/s/node_modules/beachball/lib/git/ensureSharedHistory.js:95:19)
    at ensureSharedHistory (/home/vsts/work/1/s/node_modules/beachball/lib/git/ensureSharedHistory.js:72:27)
    at getChangedPackages (/home/vsts/work/1/s/node_modules/beachball/lib/changefile/getChangedPackages.js:112:51)
    at isChangeFileNeeded (/home/vsts/work/1/s/node_modules/beachball/lib/validation/isChangeFileNeeded.js:8:73)
    at validate (/home/vsts/work/1/s/node_modules/beachball/lib/validation/validate.js:91:70)
    at /home/vsts/work/1/s/node_modules/beachball/lib/cli.js:25:37
    at Object.<anonymous> (/home/vsts/work/1/s/node_modules/beachball/lib/cli.js:59:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
```

Doing a full clone does mitigate the issue but wanted to check why it's not able to deepen commits after the update. Nothing else has changed in terms of our CI or Beachball config.

**Comment by ecraig12345** [comment]
Sorry for the slow response. That's a big enough version jump that it's hard to say what change might have caused the issue. If you're still having this issue, you can try running with `--verbose` which should show the actual git output.
